language: go

go:
  - 1.6.3
  - tip

matrix:
  allow_failures:
  - go: tip
  fast_finish: true
  env:
  - ATOM_CHANNEL=beta
  - ATOM_CHANNEL=stable

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="false"

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - APM_TEST_PACKAGES="environment"

script:
  - 'curl -s https://raw.githubusercontent.com/Arcanemagus/ci/29a99724a44985dad4cb709c6556468b1b24ac04/build-package.sh | sh'

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
