language: go

go:
  - 1.6.3
  - tip

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="false"
    - NVM_DIR="$HOME/.nvm"
  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - rm -rf "$NVM_DIR"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
  - source "$NVM_DIR/nvm.sh"
  - nvm install node
  - nvm use node

script:
  - 'curl -s https://raw.githubusercontent.com/atom/ci/2b605a18c1508c3d51d8d80e1afaf358375699e2/build-package.sh | sh'

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
